# This file defines dbt profiles for deployed dbt jobs.
default:
  target: dev # default target
  threads: 8
  outputs:
    # Doing local development with the dbt CLI?
    # Then you should create your own profile in your .dbt/profiles.yml using 'dbt init'
    # (See README.md)

    # The default target when deployed with the Databricks CLI
    # N.B. when you use dbt from the command line, it uses the profile from .dbt/profiles.yml
    dev:
      type: databricks
      method: http
      catalog: dbt
      schema: source_1 #"{{ var('dev_schema') }}"
      # The workspace host / token are provided by Databricks
      # see databricks.yml for the workspace host used for 'dev'
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 8

    # The test target when deployed with the Databricks CLI
    test:
      type: databricks
      method: http
      catalog: dbt
      schema: bronze
      # The workspace host / token are provided by Databricks
      # see databricks.yml for the workspace host used for 'prod'
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 8

    # The production target when deployed with the Databricks CLI
    prod:
      type: databricks
      method: http
      catalog: dbt
      schema: bronze
      # The workspace host / token are provided by Databricks
      # see databricks.yml for the workspace host used for 'prod'
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 8
